name: Email Automation

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Create credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT }}' > service_account.json

      - name: Run automation
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
